#公共配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
      jdbc-url: jdbc:mysql://localhost:3306/niceschool?useUnicode=true&characterEncoding=utf8

      #jdbc-url: jdbc:mysql://localhost/niceschool?useUnicode=true&characterEncoding=utf8

      username: root
      password: Zyx3527109
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 30


#mybatisPlu
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.nsapi.niceschoolapi.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
    #刷新mapper
    refresh-mapper: true
  #原生配置
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: false
#日志
logging:
  config: classpath:logback.xml
  path: D:\logs\comadmin




---
#开发环境配置
spring:
  profiles: dev
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
      url: jdbc:mysql://localhost:3306/niceschool?useUnicode=true&characterEncoding=utf8

      #url: jdbc:mysql://localhost/niceschool?useUnicode=true&characterEncoding=utf8

      username: root
      password: Zyx3527109
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 30
server:
  #端口
  port: 8080


#app:
#  appId: 2021000118604263
#  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCh+KV5ZyHRlvyUVWvyDs6FLFs2xhv6z8XU/Jp3AhXT/0BPjoQ4DvY3XkfU5bJx2htqxinqRM9WcxTRKS+4Hxlbq6YFli5puKUSQbpMvoNUjQmeU+wdh9FJOWYNV/i0w76FS+lUgWsbOtpktqxC205harTCOabr7jJZHBRzcCdjGTxIIegTeQ8XlHJRQdb4fP/ywqMczH3uIgr5WMo9rmsv4d/RFE7OI+SbcABz1AxW3RAI2KwS5dMXpuupT+snrcMOXCjLF1hXYe3ly/JtQriN1PrW3VmU5tlCB/mJOE/mEApYpebouV9/RxpL79UcZVXGwwibr5kqpgdBvT52BwVjAgMBAAECggEAcbxsVie5c7eWfYLOXhdPpexT0M6kbybfQIRw4wiv00H2IudsqQC4nICz6CezeocxoXStkjfncEk3YPiO7bfI0rphxqKCzPI/1+YXsDRHfGPdUTSVJNduewC3TL9tgWHCs09u9Uw7rc9R9E7h/8CH9Zg8ffaF5D5LVI+HPNiQj+DWjRSXwu4G/BNCiJxiCV9vI1X1S3WERQvY9fHi+5dbPhpPRGl7aJid61C/D0uuqPOBmRWMrGLGhoWBq0dBL97mKT23G73vsVmrV0zSkyWQiHncSH5E3lXtkZ54VGBkBnTyHsZRNbRR38ox97OPW9RgsSOp8ChIQ+VUotmKXyUeoQKBgQDP5vRVroNA1euAU4OlgBMlu9aZoXvScVW0wZ92T43JAwD/n66D5n+ax4tnRhrZVarfhUGDD9pwrJ3e6IR0LJqzR/3c25gvXjbxl8F8zn/wdD2mvRF/FcZhJ6k0QD5fSZFQXqGKvc56UfZWsinGU3AED8ZvjuQiqYSpY7NtXRZFLwKBgQDHcW0YJiKWMavNGXOjE0BZ4GGKxofgaKkDUm6JUyg6Rr94FjPW9BR8t3DsZdkTBrPJ3bC3kIVIVR4klGu3HRLlAd5lEj9NYVcmfNtBFdOELY8z3jGC+rHFHe4fzzEIF70ur4ozeFfclmKfO08QR3rj5Y51pjoG2NA8YNdMvlYeDQKBgAe76b7+PPe+fYJKmQ0hFJVExZj1fuu3N57/zPTTxMyDhhf8UrupaXnSjocK/pizLSYfiO5dOp0SbtUKBVNlDWQ5+2Gp8aFhed3G7XW9INlLGbgINIxrvPOETDEbaraUwAkjXBMTOIkoX2eePRuZowMjqxgfUrFPaRX8FYKuAdQVAoGAMQay2JLXQbBoGPy+rkGXOgCsOZ7f28web9Cdl2g3pUuq2WwrxhUtzBKT0aifmcu1+lNik10VRliWFkvdxp+A+4ZgEtxPb0gUUkOy6ebhncZNQ2TFKvtRI7Fdzbfyx5h+SrGf+VMF1hWpnJbJsqi/jrHpOQZpkTFOzujHQ/gt1ykCgYAhEO1T7c0sy53F+8YbbllkPMyGYS2HGi6yymn2oVpJVPwaJsGZOn33qLQtWhs0uDnB3pkY7k8szCIbaILuEF7tJgVJsmiTzvXW8YSQCSa91CCqRk1cG/32KaHiCcfHcVeoXI1gh6vKjmIxu/oe4BDr+3O9yq33fUC7GrwdsF+C2A==
#  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAofileWch0Zb8lFVr8g7OhSxbNsYb+s/F1PyadwIV0/9AT46EOA72N15H1OWycdobasYp6kTPVnMU0SkvuB8ZW6umBZYuabilEkG6TL6DVI0JnlPsHYfRSTlmDVf4tMO+hUvpVIFrGzraZLasQttOYWq0wjmm6+4yWRwUc3AnYxk8SCHoE3kPF5RyUUHW+Hz/8sKjHMx97iIK+VjKPa5rL+Hf0RROziPkm3AAc9QMVt0QCNisEuXTF6brqU/rJ63DDlwoyxdYV2Ht5cvybUK4jdT61t1ZlObZQgf5iThP5hAKWKXm6Llff0caS+/VHGVVxsMIm6+ZKqYHQb0+dgcFYwIDAQAB
#  notifyUrl: http://localhost:8080/static/jsp/notify_url.jsp
#  returnUrl: http://localhost:8080/static/jsp/return_url.jsp
#  signType: RSA2
#  charset: utf-8
#  gatewayurl: https://openapi.alipaydev.com/gateway.do